name = "status"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { }

[env.development]
vars = { }

# Environment variables to set for production:
# wrangler secret put CODA_API_TOKEN
# wrangler secret put LOCATION_CODA_API_TOKEN

# For local development, create a .dev.vars file with:
# CODA_API_TOKEN=your-coda-api-token
# LOCATION_CODA_API_TOKEN=your-location-coda-api-token